// This file is generated by ./bin/translations.
//
// It contains translations that appear before the user has logged in and
// fetched userInterfaceText from /my_data. This is bundled into the app.

const preLoginTranslations = {
  "fr": [
    {
      "id": 42,
      "key": "error.unknown.body",
      "value": "Désolé, il semble y avoir un problème. Si cela continue, essayez de réinstaller l'application."
    },
    {
      "id": 40,
      "key": "error.network.body",
      "value": "Désolé, il semble y avoir un problème avec nos ordinateurs. Veuillez réessayer plus tard."
    },
    {
      "id": 39,
      "key": "error.network.title",
      "value": "Erreur réseau"
    },
    {
      "id": 2,
      "key": "login.failed",
      "value": "Échec de la connexion. Numéro de mobile non reconnu."
    },
    {
      "id": 1,
      "key": "login.prompt",
      "value": "Quel est ton numéro de portable?"
    },
    {
      "id": 43,
      "key": "error.details",
      "value": "Détails de l'erreur:"
    },
    {
      "id": 41,
      "key": "error.unknown.title",
      "value": "Erreur inattendue"
    },
    {
      "id": 34,
      "key": "loading",
      "value": "Chargement..."
    },
    {
      "id": 3,
      "key": "login.placeholder",
      "value": "par ex. 0123456789"
    }
  ],
  "en": [
    {
      "id": 42,
      "key": "error.unknown.body",
      "value": "Sorry, there seems to be a problem. If it keeps happening, try reinstalling the app."
    },
    {
      "id": 40,
      "key": "error.network.body",
      "value": "Sorry, there seems to be a problem with our computers. Please try again later."
    },
    {
      "id": 39,
      "key": "error.network.title",
      "value": "Network error"
    },
    {
      "id": 2,
      "key": "login.failed",
      "value": "Login failed. Unrecognised mobile number."
    },
    {
      "id": 1,
      "key": "login.prompt",
      "value": "What’s your mobile number?"
    },
    {
      "id": 43,
      "key": "error.details",
      "value": "Error details:"
    },
    {
      "id": 41,
      "key": "error.unknown.title",
      "value": "Unexpected error"
    },
    {
      "id": 34,
      "key": "loading",
      "value": "Loading..."
    },
    {
      "id": 3,
      "key": "login.placeholder",
      "value": "e.g. 0123456789"
    }
  ],
  "mg": [
    {
      "id": 42,
      "key": "error.unknown.body",
      "value": "Mialatsiny, ohatran'ny misy olana. Raha mbola mitohy dia avereno ampidirina ilay rindrambaiko."
    },
    {
      "id": 40,
      "key": "error.network.body",
      "value": "Mialatsiny, ohatran'ny misy olana ny solosaina. Avereno afaka fotoana fohy"
    },
    {
      "id": 39,
      "key": "error.network.title",
      "value": "Misy olana ny tambazotram-pifandraisana"
    },
    {
      "id": 2,
      "key": "login.failed",
      "value": "Tsy nahomby ny fidirana. Misy diso ny laharana finday."
    },
    {
      "id": 1,
      "key": "login.prompt",
      "value": "Inona ny laharana finday anao?"
    },
    {
      "id": 43,
      "key": "error.details",
      "value": "Pitsopitsony amin'ny fahadisoana:"
    },
    {
      "id": 41,
      "key": "error.unknown.title",
      "value": "Fahadisoana tsy nampoizina"
    },
    {
      "id": 34,
      "key": "loading",
      "value": "Andalam-pamitana"
    },
    {
      "id": 3,
      "key": "login.placeholder",
      "value": "Oh: 0123456789"
    }
  ],
  "sw": [
    {
      "id": 42,
      "key": "error.unknown.body",
      "value": "Samahani, inaonekana kuna itilafu. Ikiendelea kutokea, jaribu kupakua tena programu."
    },
    {
      "id": 40,
      "key": "error.network.body",
      "value": "Samahani, inaonekana kuna itilafu na kompyuta zetu. Tafadhali jaribu tena baadae."
    },
    {
      "id": 39,
      "key": "error.network.title",
      "value": "Tatizo la mtandao"
    },
    {
      "id": 2,
      "key": "login.failed",
      "value": "Imeshindikana kuingia. Nambari ya simu aiyasajiliwa"
    },
    {
      "id": 1,
      "key": "login.prompt",
      "value": "Nambari yako ya simu ni ipi?"
    },
    {
      "id": 43,
      "key": "error.details",
      "value": "Maelezo ya itilafu:"
    },
    {
      "id": 41,
      "key": "error.unknown.title",
      "value": "itilafu lisilotarajiwa"
    },
    {
      "id": 34,
      "key": "loading",
      "value": "Inapakia ..."
    },
    {
      "id": 3,
      "key": "login.placeholder",
      "value": "Mfano. 0123456789"
    }
  ]
};

export default preLoginTranslations;
