// This file is generated by ./bin/translations.
//
// It contains translations that appear before the user has logged in and
// fetched userInterfaceText from /my_data. This is bundled into the app.

const preLoginTranslations = {
  "fr": [
    {
      "key": "login.prompt",
      "value": "Quel est ton numéro de portable?"
    },
    {
      "key": "login.failed",
      "value": "Échec de la connexion. Numéro de mobile non reconnu."
    },
    {
      "key": "login.placeholder",
      "value": "par ex. 0123456789"
    },
    {
      "key": "loading",
      "value": "Chargement..."
    },
    {
      "key": "error.network.title",
      "value": "Erreur réseau"
    },
    {
      "key": "error.network.body",
      "value": "Désolé, il semble y avoir un problème avec nos ordinateurs. Veuillez réessayer plus tard."
    },
    {
      "key": "error.unknown.title",
      "value": "Erreur inattendue"
    },
    {
      "key": "error.unknown.body",
      "value": "Désolé, il semble y avoir un problème. Si cela continue, essayez de réinstaller l'application."
    },
    {
      "key": "error.details",
      "value": "Détails de l'erreur:"
    }
  ],
  "en": [
    {
      "key": "login.prompt",
      "value": "What’s your mobile number?"
    },
    {
      "key": "login.failed",
      "value": "Login failed. Unrecognised mobile number."
    },
    {
      "key": "login.placeholder",
      "value": "e.g. 0123456789"
    },
    {
      "key": "loading",
      "value": "Loading..."
    },
    {
      "key": "error.network.title",
      "value": "Network error"
    },
    {
      "key": "error.network.body",
      "value": "Sorry, there seems to be a problem with our computers. Please try again later."
    },
    {
      "key": "error.unknown.title",
      "value": "Unexpected error"
    },
    {
      "key": "error.unknown.body",
      "value": "Sorry, there seems to be a problem. If it keeps happening, try reinstalling the app."
    },
    {
      "key": "error.details",
      "value": "Error details:"
    }
  ]
};

export default preLoginTranslations;
